name = "From B to A"
author = "Ripazha1333"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "536657261a7e9f8fc68eede054cb189cb4d0bcd3183d23efe244e3deb6fd21bd"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
