name = "From B to A"
author = "Ripazha1333"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfa97597c5d04665a24d4d5c0e98fde337c550f0ad1df014f0a699bc822b3988"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
