name = "From B to A"
author = "Ripazha1333"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cdc2424c319ab684ffe08d49a88c6e55260071efb938e9fe7132a30a2de1fa12"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
