name = "From B to A"
author = "Ripazha1333"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bc08121041aedd06b6ac11d34dda0c24f297be87cf689826ef4d9c9d6b05800"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
