name = "From B to A"
author = "Ripazha1333"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d72fc0934878c9f5acf8f187c1e6de099baeab5af4e0884a60212114f7725976"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
