name = "From B to A"
author = "Ripazha1333"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "888ee225a3d1e9356954109dc6a08b7ad205fbe4b724cf137e2f0289676135db"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
